theme: jekyll-theme-minimal
title: Welcome to the SCEC Unified Community Velocity Model (UCVM) Software Documentation Homepage
description: The SCEC UCVM Software provides an API used to query seismic velocity models for southern California and other regions.
